/**
 * The Builder's server functions — the only doors between the browser and the
 * lead record. Each one:
 *
 *   1. reads the session from the httpOnly cookie (never a lead id from the body),
 *   2. builds the context: service-role store, model caller, Telegram notifier,
 *      hashed client key for rate limiting,
 *   3. runs the operation from `service.server.ts`,
 *   4. returns a validated snapshot, or throws `Error(<BuilderErrorCode>)`.
 *
 * The service-role key (`SUPABASE_SERVICE_ROLE_KEY`) is used only inside these
 * handlers, through the generated `client.server.ts`; `*.server.ts` modules are
 * blocked from the client bundle by TanStack Start's import protection.
 */
import { createServerFn } from "@tanstack/react-start";
import {
  deleteCookie,
  getCookie,
  getRequest,
  getRequestHeader,
  setCookie,
} from "@tanstack/react-start/server";
import { errorCodeOf } from "./errors";
import type { Lead } from "./brief";
import type { DesignSpecDraft } from "./spec";

async function context() {
  const [
    { supabaseAdmin },
    { createStore },
    { callTool },
    session,
    { sendContactToTelegram },
    { translations },
  ] = await Promise.all([
    import("@/integrations/supabase/client.server"),
    import("./store.server"),
    import("./ai-provider.server"),
    import("./session.server"),
    import("@/lib/telegram.functions"),
    import("@/lib/i18n"),
  ]);

  const store = createStore(async (fn, args) => {
    // The generated Database type has no builder_* functions yet (types.ts is
    // regenerated by Supabase tooling after the migration is applied).
    const { data, error } = await (
      supabaseAdmin.rpc as unknown as (
        f: string,
        a: Record<string, unknown>,
      ) => Promise<{ data: unknown; error: { message: string } | null }>
    )(fn, args);
    if (error) throw new Error(error.message);
    return data;
  });

  const ip =
    getRequestHeader("cf-connecting-ip") ||
    getRequestHeader("x-forwarded-for")?.split(",")[0]?.trim() ||
    getRequestHeader("x-real-ip") ||
    undefined;

  const secure = (() => {
    try {
      return new URL(getRequest().url).protocol === "https:";
    } catch {
      return true;
    }
  })();

  return {
    store,
    ai: callTool,
    notify: async (payload: ReturnType<typeof import("./submission").toContactPayload>) => {
      await sendContactToTelegram({ data: payload });
    },
    budgetLabels: translations.CZ.contact.form.budgets,
    client: await session.clientKey(ip),
    session: session.parseSession(getCookie(session.SESSION_COOKIE)),
    onSession: (s: { leadId: string; token: string }) =>
      setCookie(session.SESSION_COOKIE, session.serializeSession(s), {
        httpOnly: true,
        secure,
        sameSite: "lax",
        path: "/",
        maxAge: session.SESSION_MAX_AGE,
      }),
  };
}

/** Maps any failure to a public error code; internal detail stays in server logs. */
function publicError(err: unknown): never {
  const code = errorCodeOf(err);
  if (code === "UNKNOWN") {
    console.error("[builder] unexpected failure", err instanceof Error ? err.name : typeof err);
    throw new Error("PERSISTENCE_UNAVAILABLE");
  }
  // A session whose lead no longer exists is cleared, so the next save starts fresh.
  if (code === "LEAD_NOT_FOUND") {
    try {
      deleteCookie("elevate_builder_session", { path: "/" });
    } catch {
      /* ignore */
    }
  }
  throw new Error(code);
}

const passthrough = (input: unknown) => input;

async function run<T>(
  op: (
    svc: typeof import("./service.server"),
    ctx: Awaited<ReturnType<typeof context>>,
  ) => Promise<T>,
) {
  try {
    const [svc, ctx] = await Promise.all([import("./service.server"), context()]);
    return await op(svc, ctx);
  } catch (err) {
    publicError(err);
  }
}

export const getBuilderLead = createServerFn({ method: "POST" }).handler(async () =>
  run(async (svc, ctx) => ({ lead: (await svc.loadSession(ctx)) as Lead | null })),
);

export const saveBuilderBrief = createServerFn({ method: "POST" })
  .inputValidator(passthrough)
  .handler(async ({ data }) => run(async (svc, ctx) => svc.saveBrief(ctx, data)));

export const generateBuilderConcepts = createServerFn({ method: "POST" })
  .inputValidator(passthrough)
  .handler(async ({ data }) =>
    run(
      async (svc, ctx) =>
        (await svc.generate(ctx, data)) as
          | { saved: true; lead: Lead }
          | { saved: false; drafts: DesignSpecDraft[] },
    ),
  );

export const resyncBuilderConcepts = createServerFn({ method: "POST" })
  .inputValidator(passthrough)
  .handler(async ({ data }) => run(async (svc, ctx) => svc.resyncConcepts(ctx, data)));

export const refineBuilderConcept = createServerFn({ method: "POST" })
  .inputValidator(passthrough)
  .handler(async ({ data }) => run(async (svc, ctx) => svc.refine(ctx, data)));

export const restoreBuilderRevision = createServerFn({ method: "POST" })
  .inputValidator(passthrough)
  .handler(async ({ data }) => run(async (svc, ctx) => svc.restore(ctx, data)));

export const selectBuilderConcept = createServerFn({ method: "POST" })
  .inputValidator(passthrough)
  .handler(async ({ data }) => run(async (svc, ctx) => svc.select(ctx, data)));

export const submitBuilderLead = createServerFn({ method: "POST" })
  .inputValidator(passthrough)
  .handler(async ({ data }) => run(async (svc, ctx) => svc.submit(ctx, data)));

/** Detaches this browser from its lead ("start over"). The lead stays on record. */
export const resetBuilderSession = createServerFn({ method: "POST" }).handler(async () => {
  deleteCookie("elevate_builder_session", { path: "/" });
  return { ok: true as const };
});
