/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWebRouteImport } from './routes/services.web'
import { Route as ServicesEshopRouteImport } from './routes/services.eshop'
import { Route as ServicesDesignRouteImport } from './routes/services.design'
import { Route as ServicesBrandingRouteImport } from './routes/services.branding'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as PricingWebRouteImport } from './routes/pricing.web'
import { Route as PricingEshopRouteImport } from './routes/pricing.eshop'
import { Route as PricingBrandingRouteImport } from './routes/pricing.branding'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebRoute = ServicesWebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesEshopRoute = ServicesEshopRouteImport.update({
  id: '/eshop',
  path: '/eshop',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDesignRoute = ServicesDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesBrandingRoute = ServicesBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => ServicesRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const PricingWebRoute = PricingWebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => PricingRoute,
} as any)
const PricingEshopRoute = PricingEshopRouteImport.update({
  id: '/eshop',
  path: '/eshop',
  getParentRoute: () => PricingRoute,
} as any)
const PricingBrandingRoute = PricingBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => PricingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/pricing/branding': typeof PricingBrandingRoute
  '/pricing/eshop': typeof PricingEshopRoute
  '/pricing/web': typeof PricingWebRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/branding': typeof ServicesBrandingRoute
  '/services/design': typeof ServicesDesignRoute
  '/services/eshop': typeof ServicesEshopRoute
  '/services/web': typeof ServicesWebRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/pricing/branding': typeof PricingBrandingRoute
  '/pricing/eshop': typeof PricingEshopRoute
  '/pricing/web': typeof PricingWebRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/branding': typeof ServicesBrandingRoute
  '/services/design': typeof ServicesDesignRoute
  '/services/eshop': typeof ServicesEshopRoute
  '/services/web': typeof ServicesWebRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/pricing/branding': typeof PricingBrandingRoute
  '/pricing/eshop': typeof PricingEshopRoute
  '/pricing/web': typeof PricingWebRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/branding': typeof ServicesBrandingRoute
  '/services/design': typeof ServicesDesignRoute
  '/services/eshop': typeof ServicesEshopRoute
  '/services/web': typeof ServicesWebRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/projects'
    | '/services'
    | '/pricing/branding'
    | '/pricing/eshop'
    | '/pricing/web'
    | '/projects/$slug'
    | '/services/branding'
    | '/services/design'
    | '/services/eshop'
    | '/services/web'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/projects'
    | '/services'
    | '/pricing/branding'
    | '/pricing/eshop'
    | '/pricing/web'
    | '/projects/$slug'
    | '/services/branding'
    | '/services/design'
    | '/services/eshop'
    | '/services/web'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/projects'
    | '/services'
    | '/pricing/branding'
    | '/pricing/eshop'
    | '/pricing/web'
    | '/projects/$slug'
    | '/services/branding'
    | '/services/design'
    | '/services/eshop'
    | '/services/web'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PricingRoute: typeof PricingRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web': {
      id: '/services/web'
      path: '/web'
      fullPath: '/services/web'
      preLoaderRoute: typeof ServicesWebRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/eshop': {
      id: '/services/eshop'
      path: '/eshop'
      fullPath: '/services/eshop'
      preLoaderRoute: typeof ServicesEshopRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/design': {
      id: '/services/design'
      path: '/design'
      fullPath: '/services/design'
      preLoaderRoute: typeof ServicesDesignRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/branding': {
      id: '/services/branding'
      path: '/branding'
      fullPath: '/services/branding'
      preLoaderRoute: typeof ServicesBrandingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/pricing/web': {
      id: '/pricing/web'
      path: '/web'
      fullPath: '/pricing/web'
      preLoaderRoute: typeof PricingWebRouteImport
      parentRoute: typeof PricingRoute
    }
    '/pricing/eshop': {
      id: '/pricing/eshop'
      path: '/eshop'
      fullPath: '/pricing/eshop'
      preLoaderRoute: typeof PricingEshopRouteImport
      parentRoute: typeof PricingRoute
    }
    '/pricing/branding': {
      id: '/pricing/branding'
      path: '/branding'
      fullPath: '/pricing/branding'
      preLoaderRoute: typeof PricingBrandingRouteImport
      parentRoute: typeof PricingRoute
    }
  }
}

interface PricingRouteChildren {
  PricingBrandingRoute: typeof PricingBrandingRoute
  PricingEshopRoute: typeof PricingEshopRoute
  PricingWebRoute: typeof PricingWebRoute
}

const PricingRouteChildren: PricingRouteChildren = {
  PricingBrandingRoute: PricingBrandingRoute,
  PricingEshopRoute: PricingEshopRoute,
  PricingWebRoute: PricingWebRoute,
}

const PricingRouteWithChildren =
  PricingRoute._addFileChildren(PricingRouteChildren)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesBrandingRoute: typeof ServicesBrandingRoute
  ServicesDesignRoute: typeof ServicesDesignRoute
  ServicesEshopRoute: typeof ServicesEshopRoute
  ServicesWebRoute: typeof ServicesWebRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesBrandingRoute: ServicesBrandingRoute,
  ServicesDesignRoute: ServicesDesignRoute,
  ServicesEshopRoute: ServicesEshopRoute,
  ServicesWebRoute: ServicesWebRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PricingRoute: PricingRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
